//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTiempo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string Task1 { get; set; }

        internal static Task FromResult(int v)
        {
            throw new NotImplementedException();
        }

        public string Description { get; set; }
        public string Client { get; set; }
        public System.DateTime Date { get; set; }
    }
}
